local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.termguicolors = true
opt.title = true
opt.mouse = "a"
opt.expandtab = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.smartindent = true
opt.undofile = true
opt.backup = false
opt.ignorecase = true
opt.smartcase = true
opt.splitright = true
opt.splitbelow = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 250
opt.timeoutlen = 500
opt.ttimeoutlen = 50
opt.wrap = false
opt.laststatus = 3
opt.showmode = false
opt.completeopt = { "menu", "menuone", "noselect" }
opt.inccommand = "split"
opt.winborder = "rounded"
-- Clipboard con +y / +p y atajos explícitos; no roba Ctrl+V (bloque visual).
opt.clipboard = ""
opt.exrc = false
vim.g.dotfiles_format_on_save = true
